packages:
  - "apps/*"
  - "packages/*"

strictPeerDependencies: false
autoInstallPeers: true

allowBuilds:
  esbuild: true
  sharp: true
  "@apollo/protobufjs": true
  "@swc/core": true
  protobufjs: true
